### ISSUE TITLE
小球弧线飞跃动画

### ISSUE THREAD

**Issue by lushuhao** [lushuhao/blog#11]
# 小球弧线飞跃动画

## 应用场景
* 商品添加到购物车
* 收能量，能量球飞到顶部

## 实现原理
    利用 translate 控制小球的移动
    transition 或者 animation 控制动画效果

## 简单实现 斜线移动

![line](https://user-images.githubusercontent.com/23313879/69491942-fab24a00-0ed6-11ea-8023-71feec7887ce.gif)

```html
<i class="ball leap" />
```

```css
.ball {
  position: absolute;
  top: 20px;
  right: 20px;
  z-index: 10;
  display: block;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background-color: green;
  transition: transform 1s;
}

.leap {
  transform: translate(-300px, 400px);
}
```
## 分成 x轴 y轴 直线移动

    斜线运动可以拆成 x轴 和 y轴
    利用 伪类 或者 嵌套两个标签实现
    实际项项目中，位置是计算除了的，两个标签更好写入移动距离
    
```html
<i class="ball leap">
  <i class="inner" />
</i>
```

```scss
.ball {
  display: block;
  position: absolute;
  top: 20px;
  right: 20px;
  z-index: 10;
  transition: transform 1s;
}

.inner {
  display: block;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background-color: green;
  transition: transform 1s;
}

.leap {
  transform: translateX(-300px);

  .inner {
    transform: translateY(400px);
  }
}
```
## 弧线运动

    熟悉的抛物线运动 拆成两个方向
    水平方向的匀速运动
    垂直方向的加速运动
    
![leap](https://user-images.githubusercontent.com/23313879/69492491-7c59a600-0ede-11ea-8a8a-9fdcaf554de3.gif)

```scss
.ball {
  transition: transform 1s linear;
}

.inner {
  transition: transform 1s ease-in;
}
```
## 贝塞尔曲线

    上面弧线不够明显，可以利用 cubic-bezier 函数
    ease-in === cubic-bezier(.42,0,1,1)
    [贝塞尔曲线可视化](https://cubic-bezier.com/#.42,0,1,1)

![image](https://user-images.githubusercontent.com/23313879/69491805-2cc2ac80-0ed5-11ea-8e7b-bf1631799926.png)![image](https://user-images.githubusercontent.com/23313879/69491778-a5753900-0ed4-11ea-8c1a-d372e9a2e73a.png)

```scss
.inner {
  transition: transform 1s cubic-bezier(.3,0,.7,0);
}
```
![leap](https://user-images.githubusercontent.com/23313879/69492493-85e30e00-0ede-11ea-89e5-3b49111d4697.gif)

## 获取位置，精确落入

```html
<p class="slot" />
```

```css
.slot {
  position: absolute;
  bottom: 100px;
  left: 20px;
  width: 40px;
  height: 30px;
  border: 1px solid #2F8E7E;
  border-radius: 20px;
}
```
```js
// 获取位置
initPosition = () => {
// 需要等页面渲染完成，再去获取实际位置
    setTimeout(() => {
      this.getSlotPosition();
      this.getBallPosition();
      console.log(this.ballPosition, this.slotPosition); // {x: 345, y: 30} {x: 41, y: 551}
    });
};

getPosition = (selector) => {
    const el = document.querySelector(selector);
    const { left, right, top, bottom } = el.getBoundingClientRect();
    return {
      x: (left + right) / 2,
      y: (top + bottom) / 2,
    };
};

getSlotPosition = () => {
  this.slotPosition = this.getPosition('.slot');
};

getBallPosition = () => {
  this.ballPosition = this.getPosition('.ball');
};
```
```js
leap = () => {
    const deltaX = this.slotPosition.x - this.ballPosition.x;
    const deltaY = this.slotPosition.y - this.ballPosition.y;
    this.ballPosition.el.style.transform = `translateX(${deltaX}px)`; // 小球外层容器移动 === .ball
    this.ballPosition.el.firstChild.style.transform = `translateY(${deltaY}px)`; // 小球移动 === .inner
  };
```
![leap2](https://user-images.githubusercontent.com/23313879/69492798-cbeda100-0ee1-11ea-9340-ee7d6771107c.gif)

可以进一步完善动画，先水平运动，再加速下落，最后渐隐
```js
leap = () => {
    const deltaX = this.slotPosition.x - this.ballPosition.x;
    const deltaY = this.slotPosition.y - this.ballPosition.y;
    const ballStyle = this.ballPosition.el.style;
    const innerStyle = this.ballPosition.el.firstChild.style;
    ballStyle.transform = `translateX(${deltaX}px)`;
    setTimeout(() => {
      innerStyle.transform = `translateY(${deltaY}px)`;
    }, 100);
    setTimeout(() => {
      ballStyle.opacity = 0;
    }, 900);
  };
```

最后，给总数 +1

![leap4](https://user-images.githubusercontent.com/23313879/69493090-54217580-0ee5-11ea-9aad-235e73a4d86a.gif)

```css
.slot {
  /*...*/
  line-height: 30px;
  text-align: center;
  transition: transform .2s;
}
```

```js
leap = () => {
    // ...
    const slotStyle = this.slotPosition.el.style;
    setTimeout(() => {
      this.setState({ energy: 21 });
      slotStyle.transform = 'scale(1.1)';
    }, 1000);
    setTimeout(() => {
      slotStyle.transform = 'scale(1)';
    }, 1200);
  };
```

```html
<p class="slot">{energy}</p>
```

## 总结
    飞跃动画初步实现了，在实际项目中，移动的距离需要根据实际去计算
    用js控制动画会导致重新渲染，对于低版本手机多个动画之间需要延迟
